name: Chemistry & Computational Chemistry Laboratory
description: Advanced computational platform for quantum chemistry, molecular dynamics,
  drug discovery, and chemical informatics research
primary_domains:
- Quantum Chemistry
- Molecular Dynamics
- Drug Discovery
- Chemical Informatics
- Catalysis Research
target_users: Computational chemists, medicinal chemists, pharmaceutical researchers
  (1-20 users)
spack_packages:
  quantum_chemistry:
  - gaussian@16 %gcc@11.4.0 +mpi
  - orca@5.0.4 %gcc@11.4.0 +mpi
  - psi4@1.8.2 %gcc@11.4.0 +mpi +python +chemps2 +dkh +gdma +pcmsolver +simint
  - nwchem@7.2.0 %gcc@11.4.0 +mpi +openmp +python +tce +nwdft
  - cp2k@2023.2 %gcc@11.4.0 +mpi +openmp +libxc +pexsi +sirius +cosma
  - molpro@2023.2 %gcc@11.4.0 +mpi
  - qchem@6.1 %gcc@11.4.0 +mpi +openmp
  - turbomole@7.7 %gcc@11.4.0 +mpi
  molecular_dynamics:
  - gromacs@2023.3 %gcc@11.4.0 +mpi +openmp +cuda +python +blas +lapack +hwloc +plumed
  - amber@22 %gcc@11.4.0 +mpi +openmp +cuda +python +update
  - namd@3.0 %gcc@11.4.0 +mpi +cuda +python
  - lammps@2023.08.02 %gcc@11.4.0 +mpi +openmp +python +molecule +class2 +kspace +manybody +mc +replica
  - openmm@8.0.0 %gcc@11.4.0 +python +cuda +opencl
  - charmm@c48b2 %gcc@11.4.0 +mpi +openmp +cuda
  - tinker@8.10.3 %gcc@11.4.0 +openmp
  enhanced_sampling:
  - plumed@2.9.0 %gcc@11.4.0 +mpi +python +gsl +matheval
  - colvars@2023.08.02 %gcc@11.4.0 +mpi +python
  - metadynminer@0.1.7 %gcc@11.4.0 +python
  - westpa@2.0 %gcc@11.4.0 +python +mpi
  drug_discovery:
  - autodock-vina@1.2.3 %gcc@11.4.0 +python
  - autodock-gpu@1.5.3 %gcc@11.4.0 +cuda +opencl
  - schrodinger@2023.3 %gcc@11.4.0 +mpi +cuda
  - openeye@2023.2.1 %gcc@11.4.0 +python
  - rdkit@2023.03.3 %gcc@11.4.0 +python +avalon +inchi +numpy +coordgen
  - openbabel@3.1.1 %gcc@11.4.0 +python +cairo
  chemical_informatics:
  - rdkit@2023.03.3 %gcc@11.4.0 +python +avalon +inchi +numpy +coordgen
  - openbabel@3.1.1 %gcc@11.4.0 +python +cairo +eigen +xml2
  - cclib@1.8 %gcc@11.4.0 +python
  - chempy@0.8.3 %gcc@11.4.0 +python
  - mordred@1.2.0 %gcc@11.4.0 +python
  - deepchem@2.7.1 %gcc@11.4.0 +python +tensorflow +torch
  - pmapper@0.3.2 %gcc@11.4.0 +python
  visualization_chemistry:
  - vmd@1.9.4a55 %gcc@11.4.0 +cuda +python +tcl +tk
  - pymol@2.5.0 %gcc@11.4.0 +python +incentive
  - chimera@1.16 %gcc@11.4.0 +python
  - chimerax@1.6.1 %gcc@11.4.0 +python
  - avogadro@1.97.0 %gcc@11.4.0 +qt +python +vtk
  - jmol@14.32.83 +java
  analysis_tools:
  - mdanalysis@2.6.1 %gcc@11.4.0 +python
  - mdtraj@1.9.9 %gcc@11.4.0 +python
  - pytraj@2.0.6 %gcc@11.4.0 +python +openmp
  - prody@2.4.1 %gcc@11.4.0 +python
  - pmda@0.4.0 %gcc@11.4.0 +python +mpi
  - cpptraj@6.19.7 %gcc@11.4.0 +mpi +openmp +cuda
  machine_learning_chem:
  - pytorch@2.0.1 %gcc@11.4.0 +cuda +distributed +kineto +magma +nccl +numa +onnx_ml +qnnpack +tensorpipe +xnnpack
  - tensorflow@2.13.0 %gcc@11.4.0 +cuda +nccl +tensorrt
  - py-scikit-learn@1.3.0 %gcc@11.4.0 +blas+lapack
  - deepchem@2.7.1 %gcc@11.4.0 +python +tensorflow +torch
  - dgl@1.1.2 %gcc@11.4.0 +python +cuda
  - torch-geometric@2.3.1 %gcc@11.4.0 +python
  python_chemistry:
  - python@3.11.5 %gcc@11.4.0 +optimizations+shared+ssl
  - py-numpy@1.25.2 %gcc@11.4.0 +blas+lapack
  - py-scipy@1.11.2 %gcc@11.4.0 +blas+lapack
  - py-matplotlib@3.7.2 %gcc@11.4.0 +movies
  - py-pandas@2.0.3 %gcc@11.4.0
  - py-jupyter@1.0.0 %gcc@11.4.0
  - py-seaborn@0.12.2 %gcc@11.4.0
  - py-plotly@5.15.0 %gcc@11.4.0
  math_libraries:
  - openblas@0.3.23 %gcc@11.4.0 +fortran +pic +shared threads=openmp
  - scalapack@2.2.0 %gcc@11.4.0 +pic +shared
  - fftw@3.3.10 %gcc@11.4.0 +mpi +openmp +pfft_patches
  - gsl@2.7.1 %gcc@11.4.0 +external-cblas
  - boost@1.82.0 %gcc@11.4.0 +mpi +python +numpy +serialization
  workflow_orchestration:
  - nextflow@23.04.1 +java
  - snakemake@7.32.4 +python
  - fireworks@2.0.3 +python
  - aiida@2.4.3 +python
aws_instance_recommendations:
  development:
    instance_type: c6i.2xlarge
    vcpus: 8
    memory_gb: 16
    storage_gb: 200
    cost_per_hour: 0.34
    use_case: Small molecule calculations and development
  quantum_chemistry:
    instance_type: hpc6a.24xlarge
    vcpus: 48
    memory_gb: 192
    storage_gb: 1000
    efa_enabled: true
    placement_group: cluster
    enhanced_networking: sr-iov
    network_performance: 50 Gbps
    cost_per_hour: 1.44
    use_case: Medium-scale quantum chemistry calculations
  large_qm_systems:
    instance_type: r6i.8xlarge
    vcpus: 32
    memory_gb: 256
    storage_gb: 2000
    cost_per_hour: 2.05
    use_case: Large quantum mechanical systems and DFT
  molecular_dynamics:
    instance_type: p4d.24xlarge
    vcpus: 96
    memory_gb: 1152
    gpu_memory_gb: 320
    gpus: 8
    storage_gb: 8000
    cost_per_hour: 32.77
    use_case: GPU-accelerated molecular dynamics
  drug_discovery:
    instance_type: p3.8xlarge
    vcpus: 32
    memory_gb: 244
    gpu_memory_gb: 64
    gpus: 4
    storage_gb: 2000
    cost_per_hour: 12.24
    use_case: Virtual screening and ML-based drug discovery
estimated_cost:
  compute: 2200
  storage: 400
  data_transfer: 150
  chemical_databases: 200
  total: 2950
research_capabilities:
- Quantum mechanical calculations (DFT, ab initio, semi-empirical)
- Classical molecular dynamics simulations
- Enhanced sampling methods (metadynamics, umbrella sampling)
- Virtual screening and drug discovery
- Chemical property prediction with ML
- Reaction mechanism studies
- Catalyst design and optimization
- Protein-ligand binding analysis
aws_data_sources:
- ChEMBL Database - Bioactive drug-like small molecules
- PubChem - Chemical substances and biological activities
- Protein Data Bank - 3D protein and nucleic acid structures
- Cambridge Structural Database - Small molecule crystal structures
demo_workflows:
- name: Drug Virtual Screening
  description: High-throughput virtual screening with AutoDock Vina
  dataset: ChEMBL approved drugs vs target protein
  expected_runtime: 4-12 hours
  cost_estimate: 36.7
- name: Molecular Dynamics Analysis
  description: GROMACS simulation of protein-ligand complex
  dataset: PDB protein structure with bound ligand
  expected_runtime: 6-24 hours
  cost_estimate: 196.6
- name: Quantum Chemistry Optimization
  description: DFT geometry optimization and frequency calculation
  dataset: Synthetic organic molecule structures
  expected_runtime: 2-8 hours
  cost_estimate: 11.5
- name: Chemical Property Prediction
  description: ML prediction of ADMET properties
  dataset: ChEMBL molecular descriptors and properties
  expected_runtime: 1-4 hours
  cost_estimate: 12.2
chemistry_features:
  qm_methods: [DFT, HF, MP2, CCSD, CASSCF, TDDFT]
  md_forcefields: [CHARMM, AMBER, OPLS, GROMOS]
  sampling_methods: [metadynamics, umbrella_sampling, REMD, WHAM]
  ml_applications: [QSAR, ADMET, drug_design, property_prediction]
mpi_optimizations:
  efa_enabled: true
  max_nodes: 16
  placement_strategy: cluster
  network_backend: efa
scaling_profiles:
  small_molecules:
    nodes: 1-2
    efficiency: 95
    use_case: Organic molecules, drug fragments
    memory_per_core_gb: 4
  medium_systems:
    nodes: 4-8
    efficiency: 90
    use_case: Proteins, large organic molecules
    memory_per_core_gb: 8
  large_biomolecules:
    nodes: 8-16
    efficiency: 85
    use_case: Protein complexes, membrane systems
    memory_per_core_gb: 16
aws_integration:
  datasets_available: 4
  demo_workflows_available: 4
  total_data_volume_tb: 85
  integration_date: '2024-01-15'
  data_access_patterns:
    cost_optimized: S3 Intelligent Tiering for simulation trajectories
    performance_optimized: EFS for active calculations
    security: Encrypted storage for proprietary drug discovery data
