name: Climate Modeling & Atmospheric Science Laboratory
description: Comprehensive climate simulation and atmospheric modeling with WRF, CESM,
  and data analysis tools
primary_domains:
- Climate Science
- Atmospheric Physics
- Meteorology
- Earth System Modeling
target_users: Climate researchers, atmospheric scientists, meteorologists (1-15 users)
spack_packages:
  climate_models:
  - wrf@4.5.0 %gcc@11.4.0 +netcdf +hdf5 +mpi +openmp
  - cesm@2.1.5 %gcc@11.4.0 +netcdf +mpi
  - cam@6.3.0 %gcc@11.4.0 +netcdf +mpi
  - clm@5.0.0 %gcc@11.4.0 +netcdf +mpi
  - pop@2.1.0 %gcc@11.4.0 +netcdf +mpi
  data_formats:
  - netcdf-c@4.9.2 %gcc@11.4.0 +mpi +parallel-netcdf +hdf5
  - netcdf-fortran@4.6.1 %gcc@11.4.0
  - hdf5@1.14.2 %gcc@11.4.0 +mpi +threadsafe +fortran
  - parallel-netcdf@1.12.3 %gcc@11.4.0
  - eccodes@2.31.0 %gcc@11.4.0 +fortran +python
  data_analysis:
  - cdo@2.2.2 %gcc@11.4.0 +netcdf +hdf5
  - nco@5.1.6 %gcc@11.4.0 +netcdf +openmpi
  - ncview@2.1.9 %gcc@11.4.0 +netcdf
  - udunits@2.2.28 %gcc@11.4.0
  - proj@9.2.1 %gcc@11.4.0
  python_climate:
  - python@3.11.5 %gcc@11.4.0 +optimizations+shared+ssl
  - py-xarray@2023.7.0 %gcc@11.4.0
  - py-dask@2023.7.1 %gcc@11.4.0
  - py-cartopy@0.21.1 %gcc@11.4.0
  - py-metpy@1.5.1 %gcc@11.4.0
  - py-iris@3.6.1 %gcc@11.4.0
  - py-esmpy@8.5.0 %gcc@11.4.0
  - py-numpy@1.25.2 %gcc@11.4.0
  - py-scipy@1.11.2 %gcc@11.4.0
  - py-matplotlib@3.7.2 %gcc@11.4.0
  - py-basemap@1.3.8 %gcc@11.4.0
  visualization:
  - paraview@5.11.2 %gcc@11.4.0 +python +mpi +osmesa
  - visit@3.3.3 %gcc@11.4.0 +mpi +python
  - grads@2.2.3 %gcc@11.4.0
  - ncl@6.6.2 %gcc@11.4.0 +hdf5 +netcdf
  workflow_orchestration:
  - nextflow@23.04.1 +java
  - snakemake@7.32.4 +python
  - cylc@8.2.4 +python
  - dask@2023.7.1 +python +distributed
aws_instance_recommendations:
  development:
    instance_type: c6i.4xlarge
    vcpus: 16
    memory_gb: 32
    storage_gb: 500
    cost_per_hour: 0.68
    use_case: Model development and testing
  regional_modeling:
    instance_type: hpc6a.12xlarge
    vcpus: 48
    memory_gb: 192
    storage_gb: 2000
    efa_enabled: true
    placement_group: cluster
    enhanced_networking: sr-iov
    network_performance: 50 Gbps
    cost_per_hour: 1.73
    use_case: Regional climate simulations with WRF
  global_modeling:
    instance_type: hpc6a.48xlarge
    vcpus: 96
    memory_gb: 384
    storage_gb: 4000
    efa_enabled: true
    placement_group: cluster
    enhanced_networking: sr-iov
    network_performance: 100 Gbps
    cost_per_hour: 2.88
    use_case: Global climate modeling with CESM
  data_analysis:
    instance_type: r6i.8xlarge
    vcpus: 32
    memory_gb: 256
    storage_gb: 1000
    cost_per_hour: 2.05
    use_case: Large dataset analysis and post-processing
estimated_cost:
  compute: 1200
  storage: 400
  data_transfer: 200
  total: 1800
research_capabilities:
- WRF regional weather and climate modeling up to 32 nodes
- CESM global climate simulations with 90% parallel efficiency
- High-resolution atmospheric dynamics simulations
- Climate data analysis and visualization workflows
- Ensemble climate projections and uncertainty quantification
- Extreme weather event modeling and analysis
- Climate-carbon cycle coupling simulations
- Downscaling of global climate models
aws_data_sources:
- ERA5 Reanalysis Data - ECMWF ERA5 atmospheric reanalysis data
- NOAA Global Forecast System - Global numerical weather prediction data
- NASA MERRA-2 Reanalysis - Modern-Era Retrospective analysis for Research and Applications
- NASA Global Precipitation Measurement - Global precipitation satellite observations
demo_workflows:
- name: WRF Regional Climate Simulation
  description: Run WRF model for hurricane tracking using GFS data
  dataset: NOAA GFS 0.25-degree global forecast data
  expected_runtime: 4-8 hours
  cost_estimate: 15.5
- name: Climate Data Analysis
  description: Analyze temperature trends using ERA5 reanalysis
  dataset: ERA5 temperature and precipitation data (1979-2023)
  expected_runtime: 1-3 hours
  cost_estimate: 6.75
- name: Ensemble Climate Projection
  description: Multi-member ensemble simulation for uncertainty quantification
  dataset: ERA5 initial conditions + CMIP6 boundary conditions
  expected_runtime: 6-12 hours
  cost_estimate: 28.8
mpi_optimizations:
  efa_enabled: true
  max_nodes: 32
  placement_strategy: cluster
  network_backend: efa
scaling_profiles:
  local_scale:
    nodes: 1-2
    efficiency: 95
    use_case: Local/urban scale modeling
    grid_resolution: 1-10 km
  regional_scale:
    nodes: 4-8
    efficiency: 90
    use_case: Regional climate modeling
    grid_resolution: 10-50 km
  global_scale:
    nodes: 16-32
    efficiency: 85
    use_case: Global climate simulations
    grid_resolution: 50-200 km
aws_integration:
  datasets_available: 4
  demo_workflows_available: 0
  total_data_volume_tb: 4080
  integration_date: '2023-12-01'
  data_access_patterns:
    cost_optimized: Use S3 Intelligent Tiering
    performance_optimized: Access from same AWS region
    security: Data encrypted in transit and at rest
