name: Genomics & Bioinformatics Laboratory
description: Complete genomics analysis with optimized bioinformatics tools for variant
  calling, RNA-seq, and genome assembly
primary_domains:
- Genomics
- Bioinformatics
- Computational Biology
- Evolutionary Biology
target_users: Genomics researchers, bioinformaticians, molecular biologists (1-20
  users)
spack_packages:
  core_aligners:
  - bwa@0.7.17 %gcc@11.4.0 +pic
  - bwa-mem2@2.2.1 %gcc@11.4.0 +sse4
  - bowtie2@2.5.0 %gcc@11.4.0 +tbb
  - star@2.7.10b %gcc@11.4.0 +shared+zlib
  - hisat2@2.2.1 %gcc@11.4.0 +sse4
  - minimap2@2.26 %gcc@11.4.0 +sse4
  - blast-plus@2.14.0 %gcc@11.4.0 +pic
  variant_calling:
  - gatk@4.4.0.0
  - samtools@1.18 %gcc@11.4.0 +curses
  - bcftools@1.18 %gcc@11.4.0 +libgsl
  - htslib@1.18 %gcc@11.4.0 +libcurl
  - picard@3.0.0
  - vcftools@0.1.16 %gcc@11.4.0
  - plink@1.90b6.26 %gcc@11.4.0
  - bedtools2@2.31.0 %gcc@11.4.0
  assembly_tools:
  - canu@2.2 %gcc@11.4.0 +pic
  - flye@2.9.2
  - spades@3.15.5 %gcc@11.4.0 +openmp
  - velvet@1.2.10 %gcc@11.4.0 +openmp
  - minia@3.2.6
  - unicycler@0.5.0
  rna_seq:
  - salmon@1.10.0 %gcc@11.4.0 +shared
  - kallisto@0.48.0 %gcc@11.4.0
  - rsem@1.3.3 %gcc@11.4.0
  workflow_orchestration:
  - nextflow@23.04.1 +java
  - snakemake@7.32.4 +python
  - cromwell@86
  - stringtie@2.2.1 %gcc@11.4.0
  - cufflinks@2.2.1 %gcc@11.4.0
  quality_control:
  - fastqc@0.12.1
  - trimmomatic@0.39
  - cutadapt@4.4
  - multiqc@1.14
  - fastp@0.23.4 %gcc@11.4.0
  python_bio:
  - python@3.11.4 %gcc@11.4.0 +optimizations+shared+ssl
  - py-biopython@1.81
  - py-pysam@0.21.0
  - py-numpy@1.25.1 ^openblas@0.3.23 threads=openmp
  - py-pandas@2.0.3
  - py-scipy@1.11.1 ^openblas@0.3.23
  - py-scikit-learn@1.3.0
  - py-matplotlib@3.7.2
  - py-seaborn@0.12.2
  - py-jupyter@1.0.0
  - py-jupyterlab@4.0.3
  r_bioconductor:
  - r@4.3.1 %gcc@11.4.0 +X+external-lapack ^openblas@0.3.23
  - r-biocmanager@1.30.21
  - r-deseq2@1.40.2
  - r-edger@3.42.4
  - r-genomicranges@1.52.0
  - r-biostrings@2.68.1
  - r-iranges@2.34.1
  - r-ggplot2@3.4.2
  - r-dplyr@1.1.2
aws_instance_recommendations:
  development:
    instance_type: c6i.2xlarge
    vcpus: 8
    memory_gb: 16
    storage_gb: 200
    cost_per_hour: 0.34
    use_case: Development and small dataset analysis
  standard_analysis:
    instance_type: r6i.4xlarge
    vcpus: 16
    memory_gb: 128
    storage_gb: 500
    cost_per_hour: 1.02
    use_case: Standard whole genome sequencing analysis
  large_cohort:
    instance_type: r6i.8xlarge
    vcpus: 32
    memory_gb: 256
    storage_gb: 1000
    cost_per_hour: 2.05
    use_case: Large cohort studies and population genomics
  assembly_intensive:
    instance_type: x2iezn.4xlarge
    vcpus: 16
    memory_gb: 512
    storage_gb: 2000
    cost_per_hour: 2.17
    use_case: Memory-intensive genome assembly and large datasets
estimated_cost:
  compute: 600
  storage: 200
  data_transfer: 100
  total: 900
research_capabilities:
- Whole genome sequencing variant calling (GATK4 best practices)
- RNA-seq differential expression analysis (STAR + DESeq2)
- Long-read genome assembly (Canu + Flye)
- Single-cell RNA-seq analysis workflow
- Metagenomics classification and assembly
- ChIP-seq peak calling and motif analysis
- Population genomics and GWAS analysis
- Phylogenomic reconstruction pipeline
aws_data_sources:
- 1000 Genomes Project - International genome sequencing consortium data
- NCBI Sequence Read Archive - Public sequencing data repository
- Genome Aggregation Database - Population genomics variant database
demo_workflows:
- name: GATK Variant Calling Demo
  description: Run GATK best practices pipeline on 1000 Genomes sample
  dataset: 1000 Genomes Project - chromosome 20 subset
  expected_runtime: 2-4 hours
  cost_estimate: 8.5
- name: RNA-seq Analysis Demo
  description: Differential expression analysis using public GTEx data
  dataset: GTEx tissue expression samples
  expected_runtime: 1-2 hours
  cost_estimate: 4.25
- name: Genome Assembly Demo
  description: Bacterial genome assembly using long-read data
  dataset: E. coli long-read sequencing from SRA
  expected_runtime: 30-60 minutes
  cost_estimate: 2.1
- name: Variant Calling Demo
  description: GATK best practices pipeline on 1000 Genomes data
  dataset: 1000 Genomes Project
  expected_runtime: 2-4
  cost_estimate: 0.81
- name: RNA-seq Analysis Demo
  description: Differential expression analysis using public data
  dataset: NCBI Sequence Read Archive
  expected_runtime: 1-2
  cost_estimate: 0.33
mpi_optimizations:
  efa_enabled: true
  max_nodes: 8
  placement_strategy: cluster
  network_backend: efa
scaling_profiles:
  single_sample:
    nodes: 1
    efficiency: 100
    use_case: Individual genome analysis
  cohort_analysis:
    nodes: 2-4
    efficiency: 90
    use_case: Small to medium cohort studies
  population_genomics:
    nodes: 4-8
    efficiency: 85
    use_case: Large-scale population studies
aws_integration:
  datasets_available: 3
  demo_workflows_available: 2
  total_data_volume_tb: 15305
  integration_date: '2023-12-01'
  data_access_patterns:
    cost_optimized: Use S3 Intelligent Tiering
    performance_optimized: Access from same AWS region
    security: Data encrypted in transit and at rest
