name: Geospatial Research & Earth Observation Laboratory
description: Comprehensive platform for remote sensing, GIS analysis, geophysics,
  and environmental modeling
primary_domains:
- Remote Sensing
- Geographic Information Systems
- Geophysics
- Environmental Modeling
- Earth Observation
target_users: Geospatial analysts, remote sensing specialists, GIS researchers, environmental
  scientists (1-25 users)
spack_packages:
  remote_sensing:
  - gdal@3.7.1 %gcc@11.4.0 +python +netcdf +hdf5 +geos +proj +curl
  - qgis@3.32.2 %gcc@11.4.0 +python +postgresql +grass +saga
  - grass@8.3.0 %gcc@11.4.0 +python +postgresql +netcdf +geos
  - saga-gis@9.1.1 %gcc@11.4.0 +python +postgresql
  - otb@9.0.0 %gcc@11.4.0 +python +opencv +fftw
  - pktools@2.6.7 %gcc@11.4.0 +python +gdal
  - snap@10.0.0 %gcc@11.4.0 +python
  python_geospatial:
  - python@3.11.5 %gcc@11.4.0 +optimizations+shared+ssl
  - py-rasterio@1.3.8 %gcc@11.4.0
  - py-geopandas@0.13.2 %gcc@11.4.0
  - py-shapely@2.0.1 %gcc@11.4.0
  - py-fiona@1.9.4 %gcc@11.4.0
  - py-pyproj@3.6.1 %gcc@11.4.0
  - py-cartopy@0.21.1 %gcc@11.4.0
  - py-folium@0.14.0 %gcc@11.4.0
  - py-geoplot@0.5.1 %gcc@11.4.0
  - py-contextily@1.3.0 %gcc@11.4.0
  satellite_processing:
  - py-earthpy@0.9.4 %gcc@11.4.0
  - py-satpy@0.43.0 %gcc@11.4.0
  - py-pyresample@1.27.1 %gcc@11.4.0
  - py-pystac@1.8.2 %gcc@11.4.0
  - py-stackstac@0.5.0 %gcc@11.4.0
  - py-sentinelsat@1.2.1 %gcc@11.4.0
  - py-earthengine-api@0.1.364 %gcc@11.4.0
  - py-planetary-computer@0.4.9 %gcc@11.4.0
  geophysics:
  - gmt@6.4.0 %gcc@11.4.0 +fftw +gdal +netcdf +pcre
  - seismic-unix@44R26 %gcc@11.4.0 +fftw
  - madagascar@3.0.1 %gcc@11.4.0 +fftw +mpi
  - geomodeller@4.0.8 %gcc@11.4.0
  - paraview@5.11.2 %gcc@11.4.0 +python +mpi +osmesa
  - visit@3.3.3 %gcc@11.4.0 +mpi +python
  analysis_libraries:
  - py-xarray@2023.7.0 %gcc@11.4.0
  - py-dask@2023.8.0 %gcc@11.4.0
  - py-numpy@1.25.2 %gcc@11.4.0
  - py-scipy@1.11.2 %gcc@11.4.0
  - py-pandas@2.0.3 %gcc@11.4.0
  - py-scikit-learn@1.3.0 %gcc@11.4.0
  - py-matplotlib@3.7.2 %gcc@11.4.0
  - py-seaborn@0.12.2 %gcc@11.4.0
  - py-plotly@5.15.0 %gcc@11.4.0
  - py-bokeh@3.2.2 %gcc@11.4.0
  image_processing:
  - py-opencv@4.8.0 %gcc@11.4.0 +python +cuda
  - py-scikit-image@0.21.0 %gcc@11.4.0
  - py-pillow@10.0.0 %gcc@11.4.0
  - py-imageio@2.31.1 %gcc@11.4.0
  - py-mahotas@1.4.13 %gcc@11.4.0
  ml_geospatial:
  - pytorch@2.0.1 %gcc@11.4.0 +cuda +nccl
  - tensorflow@2.13.0 %gcc@11.4.0 +cuda
  - py-torchgeo@0.5.1 %gcc@11.4.0
  - py-tensorflow-addons@0.21.0 %gcc@11.4.0
  - py-fastai@2.7.12 %gcc@11.4.0
  database_spatial:
  - postgresql@15.4 %gcc@11.4.0 +ssl
  - postgis@3.4.0 %gcc@11.4.0 +raster +topology
  - sqlite@3.42.0 %gcc@11.4.0 +rtree
  - spatialite@5.1.0 %gcc@11.4.0
  r_spatial:
  - r@4.3.1 %gcc@11.4.0 +X+external-lapack
  - r-sf@1.0.14 %gcc@11.4.0
  - r-terra@1.7.39 %gcc@11.4.0
  - r-raster@3.6.23 %gcc@11.4.0
  - r-leaflet@2.1.2 %gcc@11.4.0
  - r-tmap@3.3.4 %gcc@11.4.0
  - r-mapview@2.11.0 %gcc@11.4.0
aws_instance_recommendations:
  development:
    instance_type: c6i.xlarge
    vcpus: 4
    memory_gb: 8
    storage_gb: 100
    cost_per_hour: 0.17
    use_case: Development and small-scale GIS analysis
  moderate_processing:
    instance_type: c6i.4xlarge
    vcpus: 16
    memory_gb: 32
    storage_gb: 500
    cost_per_hour: 0.68
    use_case: Regional satellite data processing
  memory_intensive:
    instance_type: r6i.4xlarge
    vcpus: 16
    memory_gb: 128
    storage_gb: 1000
    cost_per_hour: 1.02
    use_case: Large raster processing and analysis
  gpu_processing:
    instance_type: g5.4xlarge
    vcpus: 16
    memory_gb: 64
    gpu_count: 1
    gpu_memory: 24 GB
    storage_gb: 1000
    cost_per_hour: 1.624
    use_case: GPU-accelerated image processing and ML
  large_scale:
    instance_type: hpc6a.24xlarge
    vcpus: 48
    memory_gb: 192
    storage_gb: 2000
    efa_enabled: true
    placement_group: cluster
    enhanced_networking: sr-iov
    network_performance: 50 Gbps
    cost_per_hour: 1.44
    use_case: Continental-scale geospatial modeling
  storage_optimized:
    instance_type: i4i.4xlarge
    vcpus: 16
    memory_gb: 128
    nvme_ssd_gb: 3750
    cost_per_hour: 1.22
    use_case: High I/O satellite data archives
estimated_cost:
  compute: 1200
  gpu: 800
  storage: 600
  satellite_data: 400
  total: 3000
research_capabilities:
- Multi-temporal satellite imagery analysis (Landsat, Sentinel, MODIS)
- Land cover classification and change detection
- Environmental monitoring and disaster response
- Urban growth modeling and planning
- Agricultural monitoring and precision farming
- Digital elevation model processing and analysis
- Geophysical data processing and visualization
- Machine learning for geospatial applications
aws_data_sources:
- Landsat Collection 2 - Landsat satellite imagery archive
- Sentinel-2 Cloud-Optimized GeoTIFFs - ESA Sentinel-2 Level-2A atmospheric corrected
  imagery
- MODIS Nadir BRDF-Adjusted Reflectance - MODIS daily surface reflectance product
- USDA NASS Cropland Data Layer - Crop-specific land cover classification
demo_workflows:
- name: Land Cover Classification
  description: Supervised classification of Sentinel-2 imagery
  dataset: Sentinel-2 Level-2A data from AWS Open Data
  expected_runtime: 2-4 hours
  cost_estimate: 11.5
- name: Urban Change Detection
  description: Multi-temporal analysis of urban expansion
  dataset: Landsat time series from Google Earth Engine
  expected_runtime: 3-6 hours
  cost_estimate: 18.75
- name: Flood Mapping
  description: SAR-based flood extent mapping
  dataset: Sentinel-1 SAR data for flood events
  expected_runtime: 4-8 hours
  cost_estimate: 22.4
- name: Agricultural Monitoring
  description: Crop type mapping and yield estimation
  dataset: MODIS NDVI time series + field boundaries
  expected_runtime: 5-10 hours
  cost_estimate: 35.2
geospatial_features:
  projections: Comprehensive coordinate reference system support
  formats: COG, GeoTIFF, Shapefile, GeoJSON, NetCDF, HDF5
  apis: STAC, OGC Web Services, Google Earth Engine
  cloud_native: Cloud-Optimized GeoTIFF and STAC workflows
mpi_optimizations:
  efa_enabled: true
  max_nodes: 16
  placement_strategy: cluster
  network_backend: efa
scaling_profiles:
  local_analysis:
    nodes: 1
    efficiency: 100
    use_case: Site-specific studies
    spatial_extent: "< 100 km\xB2"
  regional_analysis:
    nodes: 2-4
    efficiency: 95
    use_case: Regional environmental monitoring
    spatial_extent: "100 - 10,000 km\xB2"
  continental_analysis:
    nodes: 8-16
    efficiency: 85
    use_case: Continental-scale land cover mapping
    spatial_extent: "> 10,000 km\xB2"
aws_integration:
  datasets_available: 4
  demo_workflows_available: 0
  total_data_volume_tb: 5165
  integration_date: '2023-12-01'
  data_access_patterns:
    cost_optimized: Use S3 Intelligent Tiering
    performance_optimized: Access from same AWS region
    security: Data encrypted in transit and at rest
