name: Documentation Build and Deploy

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - 'domain-packs/**'
      - 'go/**/*.go'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install documentation tools
      run: |
        pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin
        pip install mkdocs-awesome-pages-plugin mkdocs-redirects
        go install github.com/swaggo/swag/cmd/swag@latest

    - name: Generate API documentation
      run: |
        cd go
        swag init -g cmd/main.go -o docs/swagger

    - name: Generate domain pack documentation
      run: |
        python scripts/generate-domain-docs.py

    - name: Build documentation
      run: |
        mkdocs build --verbose --clean

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: site/

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        custom_domain: researchwizard.app

  validate-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install validation tools
      run: |
        pip install linkchecker markdown-link-check

    - name: Validate markdown links
      run: |
        find docs -name "*.md" -exec markdown-link-check {} \;

    - name: Check for broken internal links
      run: |
        python scripts/validate-internal-links.py
